lib/pokemon_couture_web/router.ex
defmodule PokemonCoutureWeb.Router do
  use PokemonCoutureWeb, :router

  import PokemonCoutureWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user

    plug :put_root_layout, {PokemonCoutureWeb.LayoutView, :root}
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PokemonCoutureWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/clothes", ClothesController, only: [:index, :show]

  end

  # Other scopes may use custom stacks.
  # scope "/api", PokemonCoutureWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PokemonCoutureWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", PokemonCoutureWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", PokemonCoutureWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/tracker", ClothesTrackerLive

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PokemonCoutureWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/pokemon_couture_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Pokémon Couture" %></h1>
  <p>Tracking tool for clothes in Pokémon Sun & Moon.</p>
  <p>After you create an account, you can use the Clothes tracker page below.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Navigation</h2>
    <ul>
      <li>
        <%= link "Clothes tracker", to: Routes.live_path(@conn, PokemonCoutureWeb.ClothesTrackerLive) %>
      </li>
      <li>
        <%= link "List of clothes", to: Routes.clothes_path(@conn, :index) %>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Links</h2>
    <ul>
      <li>
        <a href="https://github.com/SleepyLili/pokemon-couture">Source</a>
      </li>
      <li>
        <a href="https://raru.re/@pasty">My mastodon profile</a>
      </li>
    </ul>
  </article>
</section>

<section class="phx-attributions">
  <h2> Attributions </h2>
  <p>The icon at the top is a pikachu by WEBTECHOPS LLP from the Noun Project.</p>
</section>